-- AlterTable User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mentorBankName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mentorAccountNumber" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mentorAccountName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mentorBankCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mentorSubaccountCode" TEXT;

-- AlterTable MentorGroup
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "academyName" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "benefits" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "targetMarkets" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "skillLevel" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "duration" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "telegramLink" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "discordLink" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "customBadge" TEXT;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "isPaid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "price" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "billingCycle" TEXT NOT NULL DEFAULT 'ONE_TIME';
ALTER TABLE "MentorGroup" ADD COLUMN IF NOT EXISTS "platformFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 5.0;

-- AlterTable MentorStudent
ALTER TABLE "MentorStudent" ADD COLUMN IF NOT EXISTS "paidAmount" DOUBLE PRECISION;
ALTER TABLE "MentorStudent" ADD COLUMN IF NOT EXISTS "currency" TEXT;
ALTER TABLE "MentorStudent" ADD COLUMN IF NOT EXISTS "platformFeeAmount" DOUBLE PRECISION;
ALTER TABLE "MentorStudent" ADD COLUMN IF NOT EXISTS "mentorPayoutAmount" DOUBLE PRECISION;
ALTER TABLE "MentorStudent" ADD COLUMN IF NOT EXISTS "paymentReference" TEXT;
ALTER TABLE "MentorStudent" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
