/**
 * Centralized Instrument Specifications Model for JAHZJOURNALS Risk Calculator V2
 * Supports Forex, JPY Pairs, Metals, Indices, Crypto, and Energy.
 * Every instrument defines a full broker-aware specification structure.
 */

export const ASSET_CLASSES = {
  FOREX: 'FOREX',
  METALS: 'METALS',
  INDICES: 'INDICES',
  CRYPTO: 'CRYPTO',
  ENERGY: 'ENERGY',
  CUSTOM: 'CUSTOM',
};

export const SPECIFICATION_SOURCES = {
  STANDARD: 'STANDARD',
  BROKER: 'BROKER',
  CUSTOM: 'CUSTOM',
};

export const INSTRUMENT_SPECS = {
  // Forex Majors (Standard 100,000 units, 0.0001 pip, 0.00001 tick)
  EURUSD: {
    symbol: 'EURUSD',
    displayName: 'EUR/USD',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0, // base quote value per 1.00 lot
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  GBPUSD: {
    symbol: 'GBPUSD',
    displayName: 'GBP/USD',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  AUDUSD: {
    symbol: 'AUDUSD',
    displayName: 'AUD/USD',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'AUD',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  NZDUSD: {
    symbol: 'NZDUSD',
    displayName: 'NZD/USD',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'NZD',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  USDCHF: {
    symbol: 'USDCHF',
    displayName: 'USD/CHF',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'USD',
    quoteCurrency: 'CHF',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  USDCAD: {
    symbol: 'USDCAD',
    displayName: 'USD/CAD',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'USD',
    quoteCurrency: 'CAD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },

  // Forex JPY Pairs (0.01 pip size, 0.001 tick size)
  USDJPY: {
    symbol: 'USDJPY',
    displayName: 'USD/JPY',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    tickSize: 0.001,
    contractSize: 100000,
    pipValue: 1000.0, // in JPY
    tickValue: 100.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 3,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  EURJPY: {
    symbol: 'EURJPY',
    displayName: 'EUR/JPY',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'EUR',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    tickSize: 0.001,
    contractSize: 100000,
    pipValue: 1000.0,
    tickValue: 100.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 3,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  GBPJPY: {
    symbol: 'GBPJPY',
    displayName: 'GBP/JPY',
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'GBP',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    tickSize: 0.001,
    contractSize: 100000,
    pipValue: 1000.0,
    tickValue: 100.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 3,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },

  // Metals
  XAUUSD: {
    symbol: 'XAUUSD',
    displayName: 'XAU/USD (Gold)',
    assetClass: ASSET_CLASSES.METALS,
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
    pipSize: 0.10,
    tickSize: 0.01,
    contractSize: 100,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 2,
    volumePrecision: 2,
    unitsPerLot: 100,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
    note: 'Standard contract: 1 lot = 100 oz Gold.',
  },
  XAGUSD: {
    symbol: 'XAGUSD',
    displayName: 'XAG/USD (Silver)',
    assetClass: ASSET_CLASSES.METALS,
    baseCurrency: 'XAG',
    quoteCurrency: 'USD',
    pipSize: 0.01,
    tickSize: 0.001,
    contractSize: 5000,
    pipValue: 50.0,
    tickValue: 5.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 50.0,
    pricePrecision: 3,
    volumePrecision: 2,
    unitsPerLot: 5000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },

  // Indices
  NAS100: {
    symbol: 'NAS100',
    displayName: 'NAS100 / US Tech 100',
    assetClass: ASSET_CLASSES.INDICES,
    baseCurrency: 'USD',
    quoteCurrency: 'USD',
    pipSize: 1.0,
    tickSize: 0.1,
    contractSize: 1,
    pipValue: 1.0,
    tickValue: 0.1,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 500.0,
    pricePrecision: 1,
    volumePrecision: 2,
    unitsPerLot: 1,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
    note: '1 contract = $1 per index point move.',
  },
  US30: {
    symbol: 'US30',
    displayName: 'US30 / Dow Jones 30',
    assetClass: ASSET_CLASSES.INDICES,
    baseCurrency: 'USD',
    quoteCurrency: 'USD',
    pipSize: 1.0,
    tickSize: 1.0,
    contractSize: 1,
    pipValue: 1.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 500.0,
    pricePrecision: 1,
    volumePrecision: 2,
    unitsPerLot: 1,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
  SPX500: {
    symbol: 'SPX500',
    displayName: 'SPX500 / S&P 500',
    assetClass: ASSET_CLASSES.INDICES,
    baseCurrency: 'USD',
    quoteCurrency: 'USD',
    pipSize: 1.0,
    tickSize: 0.1,
    contractSize: 1,
    pipValue: 1.0,
    tickValue: 0.1,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 500.0,
    pricePrecision: 1,
    volumePrecision: 2,
    unitsPerLot: 1,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },

  // Crypto
  BTCUSD: {
    symbol: 'BTCUSD',
    displayName: 'BTC/USD (Bitcoin)',
    assetClass: ASSET_CLASSES.CRYPTO,
    baseCurrency: 'BTC',
    quoteCurrency: 'USD',
    pipSize: 1.0,
    tickSize: 0.01,
    contractSize: 1,
    pipValue: 1.0,
    tickValue: 0.01,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 2,
    volumePrecision: 2,
    unitsPerLot: 1,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },

  // Energy
  USOIL: {
    symbol: 'USOIL',
    displayName: 'USOIL (WTI Crude Oil)',
    assetClass: ASSET_CLASSES.ENERGY,
    baseCurrency: 'USD',
    quoteCurrency: 'USD',
    pipSize: 0.01,
    tickSize: 0.01,
    contractSize: 1000,
    pipValue: 10.0,
    tickValue: 10.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 2,
    volumePrecision: 2,
    unitsPerLot: 1000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  },
};

/**
 * Returns spec for a pair string or a fallback default spec
 */
export const getInstrumentSpec = (pairSymbol) => {
  if (!pairSymbol) return { name: INSTRUMENT_SPECS.EURUSD.displayName, ...INSTRUMENT_SPECS.EURUSD };
  
  const cleanSymbol = String(pairSymbol).replace(/[^A-Z0-9]/gi, '').toUpperCase();
  
  if (INSTRUMENT_SPECS[cleanSymbol]) {
    return { name: INSTRUMENT_SPECS[cleanSymbol].displayName, ...INSTRUMENT_SPECS[cleanSymbol] };
  }

  // Fallback heuristic if symbol isn't in predefined map
  if (cleanSymbol.includes('JPY')) {
    return {
      symbol: cleanSymbol,
      name: pairSymbol,
      displayName: pairSymbol,
      assetClass: ASSET_CLASSES.FOREX,
      baseCurrency: cleanSymbol.replace('JPY', '') || 'USD',
      quoteCurrency: 'JPY',
      pipSize: 0.01,
      tickSize: 0.001,
      contractSize: 100000,
      pipValue: 1000.0,
      tickValue: 100.0,
      lotStep: 0.01,
      minLot: 0.01,
      maxLot: 100.0,
      pricePrecision: 3,
      volumePrecision: 2,
      unitsPerLot: 100000,
      specificationSource: SPECIFICATION_SOURCES.STANDARD,
    };
  }

  if (cleanSymbol.includes('XAU') || cleanSymbol.includes('GOLD')) {
    return { name: INSTRUMENT_SPECS.XAUUSD.displayName, ...INSTRUMENT_SPECS.XAUUSD };
  }

  if (cleanSymbol.includes('NAS') || cleanSymbol.includes('US30') || cleanSymbol.includes('SPX')) {
    return {
      symbol: cleanSymbol,
      name: pairSymbol,
      displayName: pairSymbol,
      assetClass: ASSET_CLASSES.INDICES,
      baseCurrency: 'USD',
      quoteCurrency: 'USD',
      pipSize: 1.0,
      tickSize: 0.1,
      contractSize: 1,
      pipValue: 1.0,
      tickValue: 0.1,
      lotStep: 0.01,
      minLot: 0.01,
      maxLot: 500.0,
      pricePrecision: 1,
      volumePrecision: 2,
      unitsPerLot: 1,
      specificationSource: SPECIFICATION_SOURCES.STANDARD,
    };
  }

  // Default Standard Forex
  return {
    symbol: cleanSymbol,
    name: pairSymbol,
    displayName: pairSymbol,
    assetClass: ASSET_CLASSES.FOREX,
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    pipValue: 10.0,
    tickValue: 1.0,
    lotStep: 0.01,
    minLot: 0.01,
    maxLot: 100.0,
    pricePrecision: 5,
    volumePrecision: 2,
    unitsPerLot: 100000,
    specificationSource: SPECIFICATION_SOURCES.STANDARD,
  };
};
