const instruments = {
  EURUSD: {
    symbol: 'EURUSD',
    displayName: 'Euro / US Dollar',
    assetClass: 'FOREX',
    decimalPlaces: 5,
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    minimumLotSize: 0.01,
    maximumLotSize: 100,
    lotSizeStep: 0.01,
    calculationSupportStatus: 'VERIFIED',
  },
  GBPUSD: {
    symbol: 'GBPUSD',
    displayName: 'British Pound / US Dollar',
    assetClass: 'FOREX',
    decimalPlaces: 5,
    pipSize: 0.0001,
    tickSize: 0.00001,
    contractSize: 100000,
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    minimumLotSize: 0.01,
    maximumLotSize: 100,
    lotSizeStep: 0.01,
    calculationSupportStatus: 'VERIFIED',
  },
  USDJPY: {
    symbol: 'USDJPY',
    displayName: 'US Dollar / Japanese Yen',
    assetClass: 'FOREX',
    decimalPlaces: 3,
    pipSize: 0.01,
    tickSize: 0.001,
    contractSize: 100000,
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
    minimumLotSize: 0.01,
    maximumLotSize: 100,
    lotSizeStep: 0.01,
    calculationSupportStatus: 'VERIFIED',
  },
  GBPJPY: {
    symbol: 'GBPJPY',
    displayName: 'British Pound / Japanese Yen',
    assetClass: 'FOREX',
    decimalPlaces: 3,
    pipSize: 0.01,
    tickSize: 0.001,
    contractSize: 100000,
    baseCurrency: 'GBP',
    quoteCurrency: 'JPY',
    minimumLotSize: 0.01,
    maximumLotSize: 100,
    lotSizeStep: 0.01,
    calculationSupportStatus: 'VERIFIED',
  },
  XAUUSD: {
    symbol: 'XAUUSD',
    displayName: 'Gold / US Dollar',
    assetClass: 'METAL',
    decimalPlaces: 2,
    pipSize: 0.1,
    tickSize: 0.01,
    contractSize: 100,
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
    minimumLotSize: 0.01,
    maximumLotSize: 50,
    lotSizeStep: 0.01,
    calculationSupportStatus: 'BROKER_DEPENDENT',
  },
};

const getInstrumentConfig = (symbol) => instruments[String(symbol || '').trim().toUpperCase()] || null;

const isVerifiedInstrument = (symbol) => getInstrumentConfig(symbol)?.calculationSupportStatus === 'VERIFIED';

module.exports = {
  instruments,
  getInstrumentConfig,
  isVerifiedInstrument,
};
